In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame({'text':['Learnbay provides NLP','Learnbay conduct assessment','People writes comments','Learnbay writes comments'],'output':[1,1,0,0]})

In [3]:
df.head()

text  output
0        Learnbay provides NLP       1
1  Learnbay conduct assessment       1
2       People writes comments       0
3     Learnbay writes comments       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv=CountVectorizer()
bag_of_words=cv.fit_transform(df['text'])

In [6]:
bag_of_words

<4x8 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [7]:
print(cv.vocabulary_)

{'learnbay': 3, 'provides': 6, 'nlp': 4, 'conduct': 2, 'assessment': 0, 'people': 5, 'writes': 7, 'comments': 1}


In [8]:
print(bag_of_words[0].toarray())
print(bag_of_words[1].toarray())
print(bag_of_words[2].toarray())
print(bag_of_words[3].toarray())

[[0 0 0 1 1 0 1 0]]
[[1 0 1 1 0 0 0 0]]
[[0 1 0 0 0 1 0 1]]
[[0 1 0 1 0 0 0 1]]


In [9]:
cv.transform(['Learnbay also provides Deep Learning and AI along with NLP']).toarray()

array([[0, 0, 0, 1, 1, 0, 1, 0]], dtype=int64)

In [10]:
# Hyperparameter tuning
cv1=CountVectorizer(max_features=2,binary=True)
bag_of_words=cv1.fit_transform(df['text'])

In [11]:
print(cv1.vocabulary_)

{'learnbay': 1, 'comments': 0}


In [12]:
import nltk
eg='Barely two days before the expiry of a Supreme Court-stipulated deadline to probe allegations raised by Hindenburg Research about misdemeanours and violations of stock market norms by the Adani group, the Securities and Exchange Board of India (SEBI) has sought at least six more months from the Court to finalise its findings. Following the bloodbath in the prices of most Adani group stocks after the publication of Hindenburg’s report in late January, the Court had responded to a PIL and set up an expert committee to investigate the causal factors behind investor losses and ascertain regulatory failures. The SEBI chief, who termed the Hindenburg-Adani-linked issues as “the elephant in the room”, was to ensure the committee gets the information it needs. Separately, the Court tasked the regulator to speedily conclude its ongoing probe into the group for violations of its regulations. It also sought a look into whether the group had flouted the minimum public shareholding norms, failed to disclose related-party transactions, and manipulated stock prices. The two-month deadline set for SEBI and the expert committee, led by former Court judge A.M. Sapre, ends on May 2. SEBI’s last-minute plea for more time, shall also affect — if not effectively derail — the deliberations of the Justice Sapre panel.'

In [13]:
eg

'Barely two days before the expiry of a Supreme Court-stipulated deadline to probe allegations raised by Hindenburg Research about misdemeanours and violations of stock market norms by the Adani group, the Securities and Exchange Board of India (SEBI) has sought at least six more months from the Court to finalise its findings. Following the bloodbath in the prices of most Adani group stocks after the publication of Hindenburg’s report in late January, the Court had responded to a PIL and set up an expert committee to investigate the causal factors behind investor losses and ascertain regulatory failures. The SEBI chief, who termed the Hindenburg-Adani-linked issues as “the elephant in the room”, was to ensure the committee gets the information it needs. Separately, the Court tasked the regulator to speedily conclude its ongoing probe into the group for violations of its regulations. It also sought a look into whether the group had flouted the minimum public shareholding norms, failed t

In [14]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [15]:
lemm= WordNetLemmatizer()
sentence= nltk.sent_tokenize(eg)
corpus=[]

for i in range(len(sentence)):
    documents=re.sub('[^a-zA-Z]',' ', sentence[i])
    documents=documents.lower()
    documents=documents.split()
    documents=[lemm.lemmatize(word) for word in documents if not word in set(stopwords.words('english'))]
    documents=' '.join(documents)
    corpus.append(documents)

In [16]:
corpus

['barely two day expiry supreme court stipulated deadline probe allegation raised hindenburg research misdemeanour violation stock market norm adani group security exchange board india sebi sought least six month court finalise finding',
 'following bloodbath price adani group stock publication hindenburg report late january court responded pil set expert committee investigate causal factor behind investor loss ascertain regulatory failure',
 'sebi chief termed hindenburg adani linked issue elephant room ensure committee get information need',
 'separately court tasked regulator speedily conclude ongoing probe group violation regulation',
 'also sought look whether group flouted minimum public shareholding norm failed disclose related party transaction manipulated stock price',
 'two month deadline set sebi expert committee led former court judge sapre end may',
 'sebi last minute plea time shall also affect effectively derail deliberation justice sapre panel']

In [17]:
cv=CountVectorizer(binary=True)
cv1=CountVectorizer()
x=cv.fit_transform(corpus).toarray()
x1=cv1.fit_transform(corpus).toarray()

In [18]:
x

array([[1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0,

In [19]:
x1

array([[1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0,

In [20]:
cv3=CountVectorizer(max_features=10,binary=True)
x3=cv3.fit_transform(corpus).toarray()
x3

array([[1, 0, 1, 0, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 1],
       [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0]], dtype=int64)

# TF-IDF

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame({'text':['Learnbay provides NLP','Learnbay conduct assessment','People writes comments','Learnbay writes comments'],'output':[1,1,0,0]})

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf= TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.        , 0.        , 0.41137791, 0.64450299,
        0.        , 0.64450299, 0.        ],
       [0.64450299, 0.        , 0.64450299, 0.41137791, 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.52640543, 0.        , 0.        , 0.        ,
        0.66767854, 0.        , 0.52640543],
       [0.        , 0.61366674, 0.        , 0.49681612, 0.        ,
        0.        , 0.        , 0.61366674]])

In [4]:
print(tfidf.idf_)

[1.91629073 1.51082562 1.91629073 1.22314355 1.91629073 1.91629073
 1.91629073 1.51082562]


In [5]:
print(tfidf.get_feature_names_out())

['assessment' 'comments' 'conduct' 'learnbay' 'nlp' 'people' 'provides'
 'writes']
